import { AuditEvent, CoverageRequirement, Patient, Payer, PriorAuthorizationRequest, Service, PayerDecision } from './types';
export type DocumentationRequirement = { key:string; label:string; value:string; suggestions:string[] };
export const patient:Patient={id:'patient-001',name:'Maya Thompson',dob:'1982-04-14',memberId:'SYN-10001',payerId:'payer-001'};
export const payer:Payer={id:'payer-001',name:'Horizon Health Plan'};
export const service:Service={id:'service-mri-knee',name:'MRI of the Knee',diagnosis:'Knee osteoarthritis'};
export const payers:Payer[]=['Horizon Health Plan','Northstar Health','SummitCare','Evergreen Health','BlueRiver Payer','Cedar Mutual','Pioneer Health Plan','Atlas Coverage','Unity Health','HarborPoint'].map((name,i)=>({id:`payer-${String(i+1).padStart(3,'0')}`,name}));
export const services:Service[]=['MRI of the Knee','CT Scan — Abdomen','Physical Therapy','Specialist Consultation','Ultrasound — Shoulder','Sleep Study','Cataract Surgery','Colonoscopy','Cardiac Stress Test','Outpatient Infusion'].map((name,i)=>({id:`service-${i+1}`,name,diagnosis:i===0?'Knee osteoarthritis':'Clinical evaluation required'}));
export function getPatients(){return [patient]} export function getPayers(){return payers} export function getServices(){return services}
export function checkCoverageRequirement():CoverageRequirement{return {required:true,explanation:'Demo payer rules indicate that prior authorization is required for this service.',documents:['Clinical indication','Symptoms and duration','Previous conservative treatment','Physical examination findings','Previous imaging']}}
export function getDocumentationRequirements():DocumentationRequirement[]{return [{key:'indication',label:'Clinical indication',value:'Persistent knee pain affecting mobility.',suggestions:['Persistent knee pain affecting mobility.','Evaluation of ongoing symptoms.','Functional limitation requiring diagnostic imaging.']},{key:'symptoms',label:'Symptoms and duration',value:'Pain for 8 months.',suggestions:['Pain for 8 months.','Intermittent symptoms for 6 months.','Progressive symptoms affecting daily activities.']},{key:'treatment',label:'Previous conservative treatment',value:'NSAIDs and physical therapy for 12 weeks.',suggestions:['NSAIDs and physical therapy for 12 weeks.','Home exercise program and activity modification.','Conservative treatment attempted without adequate improvement.']},{key:'exam',label:'Physical examination findings',value:'Reduced range of motion and joint-line tenderness.',suggestions:['Reduced range of motion and joint-line tenderness.','Pain with weight-bearing and limited flexion.','Localized tenderness with functional limitation.']},{key:'imaging',label:'Previous imaging',value:'X-ray performed 3 months ago.',suggestions:['X-ray performed 3 months ago.','Prior radiograph reviewed; MRI requested for further evaluation.','No advanced imaging completed to date.']}]}
export function validateDocumentation(d:Record<string,string>){return Object.values(d).every(v=>v.trim().length>0)}
export function buildFHIRRepresentation(r:PriorAuthorizationRequest){return {resourceType:'ServiceRequest',id:r.id,status:'active',intent:'order',code:{text:r.service.name},subject:{reference:`Patient/${r.patient.id}`,display:r.patient.name},reasonCode:[{text:r.service.diagnosis}],insurance:[{display:r.payer.name,memberId:r.patient.memberId}],supportingInformation:Object.entries(r.docs).map(([key,value])=>({type:key,text:value}))}}
export async function submitAuthorization(outcome:PriorAuthorizationRequest['outcome']):Promise<PayerDecision>{await new Promise(r=>setTimeout(r,850)); if(outcome==='Approved')return {status:'APPROVED',authorizationId:'PA-SIM-10001',decision:'Approved'}; if(outcome==='Denied')return {status:'DENIED',decision:'Denied'}; return {status:'ADDITIONAL_INFORMATION_REQUIRED',decision:'Additional Information Required'}}
export function getAuthorizationStatus(r:PriorAuthorizationRequest){return r.status} export function getAuditEvents():AuditEvent[]{return [{timestamp:'10:02:11',event:'Authorization created',actor:'Provider',description:'Draft created for Maya Thompson.'},{timestamp:'10:02:14',event:'Coverage requirements checked',actor:'PriorAuth Connect',description:'Simulated CRD result: authorization required.'},{timestamp:'10:02:18',event:'Documentation completed',actor:'Provider',description:'5 of 5 documentation items completed.'},{timestamp:'10:02:21',event:'FHIR request generated',actor:'PriorAuth Connect',description:'Simplified FHIR representation generated.'},{timestamp:'10:02:24',event:'Request submitted',actor:'PriorAuth Connect',description:'Sent to simulated payer.'},{timestamp:'10:02:27',event:'Payer decision received',actor:'Simulated Payer',description:'Simulated response received.'},{timestamp:'10:02:27',event:'Authorization approved',actor:'Simulated Payer',description:'Decision: Approved.'}]}
